#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
[ -e "${DOTBOT_DIR}"/.git ] && pushd "${BASEDIR}" >/dev/null && cd "${DOTBOT_DIR}" && git submodule sync --quiet --recursive && popd >/dev/null
git submodule update --init --recursive "${DOTBOT_DIR}"

if grep -q "VERSION_ID=\"7\"" /etc/os-release; then
    scl enable rh-python38 -- "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
else
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
fi
